services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        value: base64:lH/EZykuRRbfc4zeSReeiBWDBsUrVIZ4IjzF3lt5X1Y=
      - key: APP_ENV
        value: production
      - key: DB_HOST
        value: switchyard.proxy.rlwy.net
      - key: DB_PORT
        value: 11996
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: PtUPbnOkUxRHQzlmspllWWudfJPIsUcU