services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan config:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:lH/EZykuRRbfc4zeSReeiBWDBsUrVIZ4IjzF3lt5X1Y=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-app.onrender.com

      # Database (Railway)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: switchyard.proxy.rlwy.net
      - key: DB_PORT
        value: 11996
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: PtUPbnOkUxRHQzlmspllWWudfJPIsUcU

      # Mail (Gmail SMTP)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: bbanze16@gmail.com
      - key: MAIL_PASSWORD
        value: "emhn lbae zkfq pkhy"
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: bbanze16@gmail.com
      - key: MAIL_FROM_NAME
        value: "Biblioteca Online"

      # Outros
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
